name: ditonton
description: A new Flutter application.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  about:
    path: about
  core:
    path: core

  http: ^1.2.2
  provider: ^6.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  get_it: ^7.7.0
  sqflite: ^2.3.3+1
  path_provider: 
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
