name: ditonton
description: A new Flutter application.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  about:
    path: about
  core:
    path: core
  movie:
    path: movie
  tv_series:
    path: tv_series

  get_it: ^7.7.0
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
