name: tv_series
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  core:
    path: ../core
    
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.1.7


flutter:
